// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"khaira-catering-user/controller"
	"khaira-catering-user/helper"
	"khaira-catering-user/repository"
	"khaira-catering-user/service"
)

// Injectors from injector.go:

func InitServer() (*fiber.App, func(), error) {
	db, cleanup, err := helper.NewDb()
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepositoryImpl()
	serviceService := service.NewServiceImpl(db, repositoryRepository)
	controllerController := controller.NewControllerImpl(serviceService)
	app := NewServer(controllerController)
	return app, func() {
		cleanup()
	}, nil
}

// injector.go:

var ServerSet = wire.NewSet(helper.NewDb, repository.NewRepositoryImpl, service.NewServiceImpl, controller.NewControllerImpl, NewServer)
